[package]
name = "wordle-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { path = "../../../risc0/risc0/zkvm", default-features = false, features = ["std"] }
wordle-core = { path = "../../core" }
